apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - role: controler
    ssh:
      address: 192.168.1.22
      user: ubuntu
      port: 22
      keyPath: C:\Users\Aumenta/.ssh/id_rsa
  - role: worker
    ssh:
      address: 192.168.1.23
      user: ubuntu
      port: 22
      keyPath: C:\Users\Aumenta/.ssh/id_rsa
  - role:
    ssh:
      address: 192.168.1.24                                                                                                   
      user: ubuntu                                                                                                              
      port: 22                                                                                                                
      keyPath: C:\Users\Aumenta/.ssh/id_rsa                                                                                 
  k0s:
    version: 1.21.1+k0s.0
